linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam

run:
  timeout: 5m

linters-settings:
  goimports:
    local-prefixes: github.com/ndizazzo/task_engine
