version: "2"

run:
  timeout: 5m

linters:
  disable:
    - errcheck
    - gosec
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocritic
    - misspell
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - errcheck
          - gosec
          - ineffassign
          - unparam
          - goconst
          - gocritic
          - misspell
          - staticcheck
      - path: "mocks/.*"
        linters:
          - errcheck
          - gosec
          - unused
          - unparam
          - goconst
          - gocritic
          - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
